/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * ListExpense.java
 * Created on 2012-6-26, 11:17:25
 */
package com.view;

import com.util.SeriableUtil;
import com.vo.ExpenseLog;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Iterator;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *本类是列表类，用于操作消费记录列表
 * @author LiuZeming
 */
public class ListExpense extends javax.swing.JFrame {

    /** Creates new form ListExpense */
    //列出所有的消费记录
    public ListExpense() {
        initComponents();
        setTitle("消费记录列表");
        Map expenseMap = SeriableUtil.deserializeFile2Obj(new File("dataFolder\\ExpenseLog.obj"));
        //设置列表第一行的数据
        String[] coluName = new String[]{"id", "卡号", "电脑编号", "开始时间", "结束时间", "消费金额"};
        DefaultTableModel dtm = new DefaultTableModel(coluName, 0);
        Iterator itor = expenseMap.keySet().iterator();
        Object key = null;
        ExpenseLog expense;
        System.out.println("消费记录");
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        while (itor.hasNext()) {
            key = itor.next();
            System.out.println(key);
            expense = (ExpenseLog) expenseMap.get(key);
            System.out.println("expense>>>>" + expense.toString());
            //没有下机的默认设置
            String endDate = "-----";
            if (expense.getEndTime() != null) {
                endDate = sdf.format(expense.getEndTime());
            }
            dtm.addRow(new Object[]{expense.getId(), expense.getCardNo(),
                        expense.getComputerNo(), sdf.format(expense.getStartTime()),
                        endDate, expense.getMoney()});

        }
        //添加到列表中
        jTable1.setModel(dtm);
    }

    //通过传入的Map集合列出消费列表
    public ListExpense(Map map) {
        initComponents();
        setTitle("电脑消费记录列表");
        String[] coluName = new String[]{"id", "卡号", "电脑编号", "开始时间", "结束时间", "消费金额"};
        DefaultTableModel dtm = new DefaultTableModel(coluName, 0);
        Iterator itor = map.keySet().iterator();
        Object key = null;
        ExpenseLog expense;
        System.out.println("消费记录");
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        while (itor.hasNext()) {
            key = itor.next();
            System.out.println(key);
            expense = (ExpenseLog) map.get(key);
            System.out.println("expense>>>>" + expense.toString());
            String endDate = "-----";
            if (expense.getEndTime() != null) {
                endDate = sdf.format(expense.getEndTime());
            }
            dtm.addRow(new Object[]{expense.getId(), expense.getCardNo(),
                        expense.getComputerNo(), sdf.format(expense.getStartTime()),
                        endDate, expense.getMoney()});
        }
        jTable1.setModel(dtm);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.view.NetBarMain.class).getContext().getResourceMap(ListExpense.class);
        jTable1.setFont(resourceMap.getFont("jTable1.font")); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null", "标题 6"
            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("jTable1.columnModel.title0")); // NOI18N
        jTable1.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("jTable1.columnModel.title1")); // NOI18N
        jTable1.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("jTable1.columnModel.title2")); // NOI18N
        jTable1.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("jTable1.columnModel.title3")); // NOI18N
        jTable1.getColumnModel().getColumn(4).setHeaderValue(resourceMap.getString("jTable1.columnModel.title4")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
