/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TurnOn.java
 *
 * Created on 2012-6-21, 16:21:58
 */
package com.view;

import com.util.DateThread;
import com.util.DataUtil;
import com.util.InitSelectItem;
import com.util.JFrameUtil;
import com.util.SeriableUtil;
import com.vo.Card;
import com.vo.Computer;
import com.vo.ExpenseLog;
import java.io.File;
import java.util.Date;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JOptionPane;
import org.jdesktop.application.Action;

/**
 *本类是上机处理类
 * @author LiuZeming
 */
public class TurnOnJFrame extends javax.swing.JFrame {

    /** Creates new form TurnOn */
    public TurnOnJFrame() {
        initComponents();
        setTitle("上机界面");
        DataUtil.initComputerData();//初始化电脑数据
        DataUtil.initCardData();//初始化上网卡的信息
        InitSelectItem.initComputerNo(computerCbox, true);//初始化电脑编号下拉框
        initTimeNow();//初始化上机时间
        
    }

    /**
     * 初始化上机时间
     * 跟系统当前时间一致
     */
    private void initTimeNow() {
        DateThread dataThread = new DateThread(timeLabel);
        //dataThread.start();
    }

 

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        computerCbox = new javax.swing.JComboBox();
        cardNoTextField = new javax.swing.JTextField();
        cardPwdTextField = new javax.swing.JPasswordField();
        timeLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.view.NetBarMain.class).getContext().getResourceMap(TurnOnJFrame.class);
        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setFont(resourceMap.getFont("jLabel4.font")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setFont(resourceMap.getFont("jLabel5.font")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.view.NetBarMain.class).getContext().getActionMap(TurnOnJFrame.class, this);
        jButton1.setAction(actionMap.get("submitData")); // NOI18N
        jButton1.setFont(resourceMap.getFont("jButton1.font")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jButton2.setAction(actionMap.get("resetData")); // NOI18N
        jButton2.setFont(resourceMap.getFont("jButton2.font")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        computerCbox.setFont(resourceMap.getFont("computerCbox.font")); // NOI18N
        computerCbox.setName("computerCbox"); // NOI18N

        cardNoTextField.setFont(resourceMap.getFont("cardNoTextField.font")); // NOI18N
        cardNoTextField.setName("cardNoTextField"); // NOI18N

        cardPwdTextField.setFont(resourceMap.getFont("cardPwdTextField.font")); // NOI18N
        cardPwdTextField.setName("cardPwdTextField"); // NOI18N

        timeLabel.setFont(resourceMap.getFont("timeLabel.font")); // NOI18N
        timeLabel.setText(resourceMap.getString("timeLabel.text")); // NOI18N
        timeLabel.setName("timeLabel"); // NOI18N

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        jMenu1.setText(resourceMap.getString("jMenu1.text")); // NOI18N
        jMenu1.setFont(resourceMap.getFont("jMenu1.font")); // NOI18N
        jMenu1.setName("jMenu1"); // NOI18N

        jMenuItem1.setText(resourceMap.getString("jMenuItem1.text")); // NOI18N
        jMenuItem1.setName("jMenuItem1"); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText(resourceMap.getString("jMenuItem2.text")); // NOI18N
        jMenuItem2.setName("jMenuItem2"); // NOI18N
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText(resourceMap.getString("jMenu2.text")); // NOI18N
        jMenu2.setFont(resourceMap.getFont("jMenu2.font")); // NOI18N
        jMenu2.setName("jMenu2"); // NOI18N

        jMenuItem4.setText(resourceMap.getString("jMenuItem4.text")); // NOI18N
        jMenuItem4.setName("jMenuItem4"); // NOI18N
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(computerCbox, 0, 185, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cardPwdTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                .addComponent(cardNoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButton1)
                        .addGap(50, 50, 50)
                        .addComponent(jButton2)))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(computerCbox, 0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cardNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cardPwdTextField)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 下机按钮
     * @param evt  
     */
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TurnOffJFrame frame = new TurnOffJFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * 退出按钮
     * @param evt 
     */
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    
    /**
     * 关于按钮 用于网吧收费的提示
     * @param evt 
     */
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       AboutBox box= new AboutBox();
        JFrameUtil.centerShowJFrame(box);
         box.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TurnOnJFrame().setVisible(true);
            }
        });
    }

    /**
     * 上机事件的处理，
     * 如果上机成功，开始计费并且把电脑与卡的状态修改
     */
    @Action
    public void submitData() {
        String cardNo = cardNoTextField.getText();
        String password = new String(cardPwdTextField.getPassword());
        String cardPath = "dataFolder\\CardMap.obj";
        String computerPath = "dataFolder\\ComputerMap.obj";
        String expensePath = "dataFolder\\ExpenseLog.obj";
        Map cardMap = SeriableUtil.deserializeFile2Obj(new File(cardPath));
        Iterator itor = cardMap.values().iterator();
        //利用isLogin的值对上机的错误信息进行处理，如果符合相应的条件会修改isLogin的值
        int isLogin = 0;
        while (itor.hasNext()) {
            Card card = (Card) itor.next();
            if (card.getId().equals(cardNo) && card.getCardPwd().equals(password)) {
                if (card.getId().equals(cardNo) && card.getCardPwd().equals(password) && card.getMoney() >= 2 && card.isState() == true) {
                    Map computerMap = SeriableUtil.deserializeFile2Obj(new File(computerPath));
                    Map expenseMap = SeriableUtil.deserializeFile2Obj(new File(expensePath));
                    Computer computer = (Computer) computerMap.get(computerCbox.getSelectedItem());
                    //对卡的操作：上机成功后把卡的状态设置为在用，然后序列化到文件
                    card.setState(false);
                    cardMap.put(card.getId(), card);
                    SeriableUtil.seriableObj2File(cardMap, new File(cardPath));
                    //对电脑的操作：上机成功后把电脑的状态设置为在用，然后序列化到文件
                    computer.setState(false);
                    SeriableUtil.seriableObj2File(computerMap, new File(computerPath));
                    //对消费记录的操作，传入相关的消费信息,上机时间为当前时间
                    int expenseId = expenseMap.size()+1;
                    expenseMap.put(expenseId, new ExpenseLog(expenseId, computer.getId(), card.getId(), new Date(), null, 0));
                    SeriableUtil.seriableObj2File(expenseMap, new File(expensePath));
                    isLogin = 1;
                } else if (card.getId().equals(cardNo) && card.getCardPwd().equals(password) && card.getMoney() < 2) {
                    isLogin = 2;
                } else if (card.getId().equals(cardNo) && card.getCardPwd().equals(password) && card.isState() == false) {
                    isLogin = 3;
                }
            }
        }
        checkData(isLogin);
    }


    /**
     *  处理验证数据
     * 参数为1 登录成功
     * 参数为2 用户名密码正确但余额不足
     * 参数为3 用户名密码正确但正在使用
     * 参数为0 用户名或者密码错误
     * @param isLogin 代表登录状态的值
     */
    private void checkData(int isLogin) {
        if (isLogin == 1) {
            JOptionPane.showMessageDialog(rootPane, "恭喜你，上机成功！", "上机成功", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);//上机成功后关闭窗口
        } else if (isLogin == 2) {
            JOptionPane.showMessageDialog(rootPane, "余额不足，请充值！", "余额不足", JOptionPane.WARNING_MESSAGE);
        } else if (isLogin == 3) {
            JOptionPane.showMessageDialog(rootPane, "此卡正在使用中!", "正在使用", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane, "卡号或者密码不正确，请重新输入！", "验证出错", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * 重置按钮的操作
     * 重置所有的输入框，电脑编号下拉框 
     * 刷新系统时间
     */
    @Action
    public void resetData() {
        cardNoTextField.setText("");
        cardPwdTextField.setText("");
        initTimeNow();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cardNoTextField;
    private javax.swing.JPasswordField cardPwdTextField;
    private javax.swing.JComboBox computerCbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables
}
